debug: Added scripts for debugging (currently commented out)

diff --git a/code/.local/bin/code b/code/.local/bin/code
--- a/code/.local/bin/code
+++ b/code/.local/bin/code
@@ -3,26 +3,31 @@
 #contributed by @Lazy Ren at StackOverflow
 #See https://stackoverflow.com/questions/62201080/is-it-possible-to-use-the-code-command-in-sshed-terminal-to-open-vs-code-on-l
 
-max_retry=10                                                                            
+max_retry=10
 for i in $(seq 1 $max_retry); do
-    recent_folder=$(ls -d ~/.vscode-server/cli/servers/*/ -t | head -n1 | tail -1)                                                             
-    script=$(echo $recent_folder/server/bin/remote-cli/code)   
-    if [[ -z ${script} ]]                                                    
-    then                                                                     
-        echo "VSCode remote script not found"                                
-        exit 1                                                               
-    fi                                                                       
-    socket=$(ls /run/user/$UID/vscode-ipc-* -t | head -n$i | tail -1)        
-    if [[ -z ${socket} ]]                                                    
-    then                                                                     
-        echo "VSCode IPC socket not found"                                   
-        exit 1                                                               
-    fi                                                                       
-    export VSCODE_IPC_HOOK_CLI=${socket}                                     
-    ${script} $@ 2>/dev/null                                                             
-    if [ "$?" -eq "0" ]; then                                                
-        exit 0                                                               
-    fi                                                                       
-done                                                                         
-                                                                             
+    recent_folder=$(ls -d ~/.vscode-server/cli/servers/*/ -t | head -n1 | tail -1)
+    script=$(echo $recent_folder/server/bin/remote-cli/code)
+    if [[ -z ${script} ]]; then
+        echo "VSCode remote script not found"
+        exit 1
+    fi
+    #echo "VSCode script path: $script"
+
+    socket=$(ls /run/user/$UID/vscode-ipc-* -t | head -n$i | tail -1)
+    if [[ -z ${socket} ]]; then
+        echo "VSCode IPC socket not found"
+        exit 1
+    fi
+    #echo "VSCode IPC socket: $socket"
+
+    export VSCODE_IPC_HOOK_CLI=${socket}
+    ${script} $@ 2>/dev/null
+    if [ "$?" -eq "0" ]; then
+        echo "VS Code command executed successfully"
+        exit 0
+    fi
+    #echo "Attempt $i: Failed to connect to VS Code"
+done
+
 echo "Failed to find valid VS Code window"
+
